name: CI Build and Test

on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Run Tests
        run: npm test

      - name: Archive Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
