name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev  # Trigger workflow on push to 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (if applicable)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # Deploy to the Dev environment
      - name: Deploy to Dev environment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl apply -f k8s/dev-deployment.yaml
