name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev  # Trigger workflow on push to 'dev' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies (if applicable)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            echo "package.json found. Installing dependencies..."
            npm install
          else
            echo "No package.json found. Skipping dependency installation."
          fi

      # Validate Kubernetes Config
      - name: Validate Kubernetes Config
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          kubectl cluster-info

      # Deploy to the Dev environment
      - name: Deploy to Dev environment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "Applying Kubernetes deployment..."
          kubectl apply -f k8s/dev-deployment.yaml

      # Verify Deployment
      - name: Verify Deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo "Verifying pods in the Dev environment..."
          kubectl get pods -o wide
